github_username: stg-book

# Site wide configuration

# url: 
title: Swift Translation Guide for Objective-C Developers
description: > # this means to ignore newlines until "baseurl:"
  A guide to using Swift for existing Objective-C developers.
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Maurice Kelly
  email: stgbook@swift-translation.guide
  twitter: mauricerkelly
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
